### ISSUE TITLE
Substituir interfaces.hpp

### ISSUE THREAD

**Issue by afmireski** [afmireski/apoCalculator#23]
# Description
Refatorar `interfaces.hpp` seguindo esse [calculator.hpp](https://replit.com/@LUCIOGERONIMO/APOO-2023-1).

# Tasks
- [x] Refatorar `interfaces.hpp`;
- [x] Refatorar `display.hpp`;
- [x] Refatorar `key.hpp`;
- [x] Refatorar `keyboard.hpp`;
- [x] Refatorar `cpu.hpp`;
- [x] `CHANGELOG.md`;
